[env:cyd]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 460800
board_build.partitions = default.csv

build_flags =
  -DBOARD_HAS_PSRAM=0
  ; === TFT_eSPI (framebuffer only, no fonts needed) ===
  -DUSER_SETUP_LOADED=1
  -DILI9341_2_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DTFT_BL=21
  -DLOAD_GLCD=0
  -DLOAD_FONT2=0
  -DLOAD_FONT4=0
  -DLOAD_FONT6=0
  -DLOAD_FONT7=0
  -DLOAD_FONT8=0
  -DLOAD_GFXFF=0
  -DSPI_FREQUENCY=55000000
  -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000

lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.1.0
  tzapu/WiFiManager@^2.0.17
